/*
# Add social feed, update logs, and profile tables for SEA TRIBE

1. New Tables
- `social_posts`: community feed posts with optional media URL, like/share counts, and author character name.
- `social_likes`: per-post like records keyed by character name to prevent duplicate likes.
- `social_comments`: comments on feed posts with author and timestamp.
- `update_logs`: admin changelog entries with version, title, body, category, and author.
- `profile_settings`: per-UCP-account profile data (avatar URL, display name, bio) with locked username.

2. Security
- RLS enabled on every new table.
- Portal has no sign-in screen, so anon + authenticated roles get CRUD access (community data is intentionally shared).

3. Seed data
- Inserts sample social posts, comments, update logs, and a profile record for the `saki` account.
*/

CREATE TABLE IF NOT EXISTS social_posts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ucp_id bigint NOT NULL REFERENCES ucp_accounts(id) ON DELETE CASCADE,
  character_name text,
  content text NOT NULL,
  media_url text,
  media_type text DEFAULT 'image',
  likes_count integer NOT NULL DEFAULT 0,
  comments_count integer NOT NULL DEFAULT 0,
  shares_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS social_likes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint NOT NULL REFERENCES social_posts(id) ON DELETE CASCADE,
  character_name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (post_id, character_name)
);

CREATE TABLE IF NOT EXISTS social_comments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id bigint NOT NULL REFERENCES social_posts(id) ON DELETE CASCADE,
  ucp_id bigint NOT NULL REFERENCES ucp_accounts(id) ON DELETE CASCADE,
  character_name text,
  content text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS update_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  version text NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  category text NOT NULL DEFAULT 'general',
  author text NOT NULL DEFAULT 'Developer',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS profile_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ucp_id bigint NOT NULL UNIQUE REFERENCES ucp_accounts(id) ON DELETE CASCADE,
  avatar_url text NOT NULL DEFAULT '',
  display_name text NOT NULL DEFAULT '',
  bio text NOT NULL DEFAULT '',
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS social_posts_created_at_idx ON social_posts(created_at DESC);
CREATE INDEX IF NOT EXISTS social_likes_post_id_idx ON social_likes(post_id);
CREATE INDEX IF NOT EXISTS social_comments_post_id_idx ON social_comments(post_id);
CREATE INDEX IF NOT EXISTS update_logs_created_at_idx ON update_logs(created_at DESC);

ALTER TABLE social_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE social_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE social_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE update_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE profile_settings ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['social_posts','social_likes','social_comments','update_logs','profile_settings'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS "public_select_%s" ON %I', table_name, table_name);
    EXECUTE format('DROP POLICY IF EXISTS "public_insert_%s" ON %I', table_name, table_name);
    EXECUTE format('DROP POLICY IF EXISTS "public_update_%s" ON %I', table_name, table_name);
    EXECUTE format('DROP POLICY IF EXISTS "public_delete_%s" ON %I', table_name, table_name);
    EXECUTE format('CREATE POLICY "public_select_%s" ON %I FOR SELECT TO anon, authenticated USING (true)', table_name, table_name);
    EXECUTE format('CREATE POLICY "public_insert_%s" ON %I FOR INSERT TO anon, authenticated WITH CHECK (true)', table_name, table_name);
    EXECUTE format('CREATE POLICY "public_update_%s" ON %I FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true)', table_name, table_name);
    EXECUTE format('CREATE POLICY "public_delete_%s" ON %I FOR DELETE TO anon, authenticated USING (true)', table_name, table_name);
  END LOOP;
END $$;

-- Seed social posts
INSERT INTO social_posts (ucp_id, character_name, content, media_url, media_type, likes_count, comments_count, shares_count)
SELECT id, 'Saki_Valentine', 'Season 04 dev build is looking insane. New night market district is almost ready for release.', NULL, 'image', 34, 8, 5
FROM ucp_accounts WHERE username = 'saki'
AND NOT EXISTS (SELECT 1 FROM social_posts WHERE character_name = 'Saki_Valentine' AND content LIKE 'Season 04 dev build%');

INSERT INTO social_posts (ucp_id, character_name, content, media_url, media_type, likes_count, comments_count, shares_count)
SELECT id, 'Mikaela_Rose', 'Anyone else hyped for the afterglow update? The new lighting alone changes everything.', NULL, 'image', 52, 14, 3
FROM ucp_accounts WHERE username = 'saki'
AND NOT EXISTS (SELECT 1 FROM social_posts WHERE character_name = 'Mikaela_Rose' AND content LIKE 'Anyone else hyped%');

-- Seed social comments
INSERT INTO social_comments (post_id, ucp_id, character_name, content)
SELECT p.id, p.ucp_id, 'Rex_Moreno', 'Cannot wait to test the new vehicles.'
FROM social_posts p WHERE p.character_name = 'Saki_Valentine' AND p.content LIKE 'Season 04 dev build%'
AND NOT EXISTS (SELECT 1 FROM social_comments c WHERE c.post_id = p.id AND c.character_name = 'Rex_Moreno');

-- Seed update logs
INSERT INTO update_logs (version, title, body, category, author)
SELECT 'v4.0.0', 'Season 04: Afterglow', 'Added night market district, 12 new vehicles, reworked city lighting, and performance optimizations.', 'feature', 'Developer'
WHERE NOT EXISTS (SELECT 1 FROM update_logs WHERE version = 'v4.0.0');
INSERT INTO update_logs (version, title, body, category, author)
SELECT 'v3.8.2', 'Hotfix: Economy balance', 'Fixed bank transfer exploit and adjusted payout rates for delivery missions.', 'fix', 'Developer'
WHERE NOT EXISTS (SELECT 1 FROM update_logs WHERE version = 'v3.8.2');
INSERT INTO update_logs (version, title, body, category, author)
SELECT 'v3.8.0', 'Community systems update', 'Added forum, social feed, and profile settings to the UCP portal.', 'feature', 'Developer'
WHERE NOT EXISTS (SELECT 1 FROM update_logs WHERE version = 'v3.8.0');

-- Seed profile settings
INSERT INTO profile_settings (ucp_id, avatar_url, display_name, bio)
SELECT id, '', 'Saki', 'Lead developer of SEA TRIBE Roleplay. Building the city, one block at a time.'
FROM ucp_accounts WHERE username = 'saki'
AND NOT EXISTS (SELECT 1 FROM profile_settings WHERE ucp_id = (SELECT id FROM ucp_accounts WHERE username = 'saki'));