/*
# Add donations table for SEA TRIBE top-up/donation system

1. New Tables
- `donations`: records of donation/top-up transactions with player name, amount, credits, payment method, voucher code, and status.

2. Security
- RLS enabled. Anon + authenticated CRUD (community portal, no sign-in screen).

3. Seed data
- Inserts sample donation packages as configuration rows.
*/

CREATE TABLE IF NOT EXISTS donations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_name text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  credits integer NOT NULL DEFAULT 0,
  payment_method text NOT NULL DEFAULT 'qris',
  voucher_code text,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS donation_packages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label text NOT NULL,
  amount numeric NOT NULL,
  credits integer NOT NULL,
  is_popular boolean NOT NULL DEFAULT false,
  display_order integer NOT NULL DEFAULT 0
);

ALTER TABLE donations ENABLE ROW LEVEL SECURITY;
ALTER TABLE donation_packages ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['donations','donation_packages'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS "public_select_%s" ON %I', table_name, table_name);
    EXECUTE format('DROP POLICY IF EXISTS "public_insert_%s" ON %I', table_name, table_name);
    EXECUTE format('DROP POLICY IF EXISTS "public_update_%s" ON %I', table_name, table_name);
    EXECUTE format('DROP POLICY IF EXISTS "public_delete_%s" ON %I', table_name, table_name);
    EXECUTE format('CREATE POLICY "public_select_%s" ON %I FOR SELECT TO anon, authenticated USING (true)', table_name, table_name);
    EXECUTE format('CREATE POLICY "public_insert_%s" ON %I FOR INSERT TO anon, authenticated WITH CHECK (true)', table_name, table_name);
    EXECUTE format('CREATE POLICY "public_update_%s" ON %I FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true)', table_name, table_name);
    EXECUTE format('CREATE POLICY "public_delete_%s" ON %I FOR DELETE TO anon, authenticated USING (true)', table_name, table_name);
  END LOOP;
END $$;

INSERT INTO donation_packages (label, amount, credits, is_popular, display_order)
SELECT 'Starter', 25000, 250, false, 1
WHERE NOT EXISTS (SELECT 1 FROM donation_packages WHERE label = 'Starter');
INSERT INTO donation_packages (label, amount, credits, is_popular, display_order)
SELECT 'Tribal', 50000, 550, false, 2
WHERE NOT EXISTS (SELECT 1 FROM donation_packages WHERE label = 'Tribal');
INSERT INTO donation_packages (label, amount, credits, is_popular, display_order)
SELECT 'Warrior', 100000, 1200, true, 3
WHERE NOT EXISTS (SELECT 1 FROM donation_packages WHERE label = 'Warrior');
INSERT INTO donation_packages (label, amount, credits, is_popular, display_order)
SELECT 'Legend', 250000, 3200, false, 4
WHERE NOT EXISTS (SELECT 1 FROM donation_packages WHERE label = 'Legend');
INSERT INTO donation_packages (label, amount, credits, is_popular, display_order)
SELECT 'Mythic', 500000, 7000, false, 5
WHERE NOT EXISTS (SELECT 1 FROM donation_packages WHERE label = 'Mythic');