/*
# Create SEA TRIBE portal tables

1. New Tables
- `ucp_accounts`: public community account references matching the legacy SQL structure.
- `characters`: SA-MP character records with level, economy, skin, status, and coordinates.
- `vehicles`: vehicle records mapped to a character and model ID for the vehicle garage.
- `forum_categories`: forum sections and display ordering.
- `forum_topics`: community topics, pinned/locked flags, views, and author metadata.
- `forum_replies`: replies attached to forum topics.
- `announcements`: active server news items.

2. Compatibility
- Integer identity IDs and legacy column names mirror the supplied MySQL schema.
- `vehicles` is added because the supplied schema references vehicle assets but does not define a vehicle table.

3. Security
- RLS is enabled on every table.
- This portal currently has no sign-in screen, so the community data is intentionally shared and readable/writable by anon and authenticated roles.
- Four separate CRUD policies are defined for every table.

4. Seed data
- Adds the initial SEA TRIBE account, characters, vehicles, forum categories, topics, replies, and announcements only when their identifying records do not already exist.
*/

CREATE TABLE IF NOT EXISTS ucp_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  email text NOT NULL UNIQUE,
  password text,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_login timestamptz,
  is_admin boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS characters (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ucp_id bigint NOT NULL REFERENCES ucp_accounts(id) ON DELETE CASCADE,
  name text NOT NULL UNIQUE,
  password text,
  level integer NOT NULL DEFAULT 1,
  money integer NOT NULL DEFAULT 5000,
  bank integer NOT NULL DEFAULT 0,
  skin integer NOT NULL DEFAULT 2,
  age integer NOT NULL DEFAULT 25,
  gender boolean NOT NULL DEFAULT false,
  health numeric NOT NULL DEFAULT 100,
  armor numeric NOT NULL DEFAULT 0,
  pos_x numeric NOT NULL DEFAULT 0,
  pos_y numeric NOT NULL DEFAULT 0,
  pos_z numeric NOT NULL DEFAULT 0,
  interior integer NOT NULL DEFAULT 0,
  virtual_world integer NOT NULL DEFAULT 0,
  is_online boolean NOT NULL DEFAULT false,
  is_banned boolean NOT NULL DEFAULT false,
  ban_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_login timestamptz
);

CREATE TABLE IF NOT EXISTS vehicles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id bigint NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
  model_id integer NOT NULL,
  name text NOT NULL,
  plate text NOT NULL UNIQUE,
  color text NOT NULL DEFAULT 'Pearl white',
  fuel integer NOT NULL DEFAULT 100,
  health numeric NOT NULL DEFAULT 1000,
  is_spawned boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS forum_categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  icon text NOT NULL DEFAULT 'comments',
  display_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS forum_topics (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id bigint NOT NULL REFERENCES forum_categories(id) ON DELETE CASCADE,
  ucp_id bigint NOT NULL REFERENCES ucp_accounts(id) ON DELETE CASCADE,
  character_name text,
  title text NOT NULL,
  content text NOT NULL,
  is_pinned boolean NOT NULL DEFAULT false,
  is_locked boolean NOT NULL DEFAULT false,
  views integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS forum_replies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic_id bigint NOT NULL REFERENCES forum_topics(id) ON DELETE CASCADE,
  ucp_id bigint NOT NULL REFERENCES ucp_accounts(id) ON DELETE CASCADE,
  character_name text,
  content text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  content text NOT NULL,
  type text NOT NULL DEFAULT 'info',
  author text NOT NULL DEFAULT 'Admin',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS characters_ucp_id_idx ON characters(ucp_id);
CREATE INDEX IF NOT EXISTS vehicles_character_id_idx ON vehicles(character_id);
CREATE INDEX IF NOT EXISTS forum_topics_category_id_idx ON forum_topics(category_id);
CREATE INDEX IF NOT EXISTS forum_topics_updated_at_idx ON forum_topics(updated_at DESC);
CREATE INDEX IF NOT EXISTS forum_replies_topic_id_idx ON forum_replies(topic_id);

ALTER TABLE ucp_accounts ENABLE ROW LEVEL SECURITY;
ALTER TABLE characters ENABLE ROW LEVEL SECURITY;
ALTER TABLE vehicles ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE forum_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['ucp_accounts','characters','vehicles','forum_categories','forum_topics','forum_replies','announcements'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS "public_select_%s" ON %I', table_name, table_name);
    EXECUTE format('DROP POLICY IF EXISTS "public_insert_%s" ON %I', table_name, table_name);
    EXECUTE format('DROP POLICY IF EXISTS "public_update_%s" ON %I', table_name, table_name);
    EXECUTE format('DROP POLICY IF EXISTS "public_delete_%s" ON %I', table_name, table_name);
    EXECUTE format('CREATE POLICY "public_select_%s" ON %I FOR SELECT TO anon, authenticated USING (true)', table_name, table_name);
    EXECUTE format('CREATE POLICY "public_insert_%s" ON %I FOR INSERT TO anon, authenticated WITH CHECK (true)', table_name, table_name);
    EXECUTE format('CREATE POLICY "public_update_%s" ON %I FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true)', table_name, table_name);
    EXECUTE format('CREATE POLICY "public_delete_%s" ON %I FOR DELETE TO anon, authenticated USING (true)', table_name, table_name);
  END LOOP;
END $$;

INSERT INTO ucp_accounts (username, email, password, is_admin)
VALUES ('saki', 'saki@seatribe.gg', NULL, true)
ON CONFLICT (username) DO NOTHING;

INSERT INTO characters (ucp_id, name, level, money, bank, skin, age, gender, health, armor, is_online, last_login)
SELECT id, 'Saki_Valentine', 10, 125000, 480000, 7, 26, false, 100, 65, true, now()
FROM ucp_accounts WHERE username = 'saki'
AND NOT EXISTS (SELECT 1 FROM characters WHERE name = 'Saki_Valentine');

INSERT INTO characters (ucp_id, name, level, money, bank, skin, age, gender, health, armor, is_online)
SELECT id, 'Mikaela_Rose', 24, 84200, 212000, 141, 23, true, 100, 30, false
FROM ucp_accounts WHERE username = 'saki'
AND NOT EXISTS (SELECT 1 FROM characters WHERE name = 'Mikaela_Rose');

INSERT INTO characters (ucp_id, name, level, money, bank, skin, age, gender, health, armor, is_online)
SELECT id, 'Rex_Moreno', 7, 29000, 68000, 29, 31, false, 83, 0, false
FROM ucp_accounts WHERE username = 'saki'
AND NOT EXISTS (SELECT 1 FROM characters WHERE name = 'Rex_Moreno');

INSERT INTO vehicles (character_id, model_id, name, plate, color, fuel, health, is_spawned)
SELECT id, 541, 'Annis Elegy Retro', 'ST-0420', 'Neon pink', 82, 968, true FROM characters WHERE name = 'Saki_Valentine'
AND NOT EXISTS (SELECT 1 FROM vehicles WHERE plate = 'ST-0420');
INSERT INTO vehicles (character_id, model_id, name, plate, color, fuel, health, is_spawned)
SELECT id, 411, 'Grotti Turismo', 'ST-1188', 'Obsidian black', 64, 884, false FROM characters WHERE name = 'Saki_Valentine'
AND NOT EXISTS (SELECT 1 FROM vehicles WHERE plate = 'ST-1188');
INSERT INTO vehicles (character_id, model_id, name, plate, color, fuel, health, is_spawned)
SELECT id, 562, 'Elegy Street Spec', 'ST-2307', 'Pearl white', 91, 996, false FROM characters WHERE name = 'Mikaela_Rose'
AND NOT EXISTS (SELECT 1 FROM vehicles WHERE plate = 'ST-2307');

INSERT INTO forum_categories (name, description, icon, display_order)
SELECT 'Server Announcements', 'Official news and updates from the SEA TRIBE staff.', 'bullhorn', 1
WHERE NOT EXISTS (SELECT 1 FROM forum_categories WHERE name = 'Server Announcements');
INSERT INTO forum_categories (name, description, icon, display_order)
SELECT 'General Discussion', 'Talk about roleplay, crews, events, and everything in between.', 'comments', 2
WHERE NOT EXISTS (SELECT 1 FROM forum_categories WHERE name = 'General Discussion');
INSERT INTO forum_categories (name, description, icon, display_order)
SELECT 'Guides & Tutorials', 'Help new players find their way around the city.', 'book', 3
WHERE NOT EXISTS (SELECT 1 FROM forum_categories WHERE name = 'Guides & Tutorials');
INSERT INTO forum_categories (name, description, icon, display_order)
SELECT 'Bug Reports', 'Report issues so the team can investigate them.', 'bug', 4
WHERE NOT EXISTS (SELECT 1 FROM forum_categories WHERE name = 'Bug Reports');

INSERT INTO forum_topics (category_id, ucp_id, character_name, title, content, is_pinned, views, updated_at)
SELECT c.id, a.id, 'Saki_Valentine', 'Season 04: Afterglow is nearly here', 'New districts, new vehicles, and the night market are coming this weekend. Read the complete update notes here.', true, 482, now()
FROM forum_categories c, ucp_accounts a WHERE c.name = 'Server Announcements' AND a.username = 'saki'
AND NOT EXISTS (SELECT 1 FROM forum_topics WHERE title = 'Season 04: Afterglow is nearly here');
INSERT INTO forum_topics (category_id, ucp_id, character_name, title, content, is_pinned, views, updated_at)
SELECT c.id, a.id, 'Mikaela_Rose', 'Share your best night-run routes', 'The city looks unreal after the latest lighting pass. What are your favorite routes?', false, 196, now() - interval '1 hour'
FROM forum_categories c, ucp_accounts a WHERE c.name = 'General Discussion' AND a.username = 'saki'
AND NOT EXISTS (SELECT 1 FROM forum_topics WHERE title = 'Share your best night-run routes');
INSERT INTO forum_topics (category_id, ucp_id, character_name, title, content, is_pinned, views, updated_at)
SELECT c.id, a.id, 'Rex_Moreno', 'How to make your first 100k', false, false, 318, now() - interval '3 hours'
FROM forum_categories c, ucp_accounts a WHERE c.name = 'Guides & Tutorials' AND a.username = 'saki'
AND NOT EXISTS (SELECT 1 FROM forum_topics WHERE title = 'How to make your first 100k');

INSERT INTO announcements (title, content, type, author)
SELECT 'Season 04: Afterglow', 'New districts, vehicles, and a night market are landing this weekend.', 'success', 'Developer'
WHERE NOT EXISTS (SELECT 1 FROM announcements WHERE title = 'Season 04: Afterglow');
INSERT INTO announcements (title, content, type, author)
SELECT 'Welcome to SEA TRIBE Roleplay', 'The official community portal is now online. Choose your character and join the city.', 'info', 'Admin'
WHERE NOT EXISTS (SELECT 1 FROM announcements WHERE title = 'Welcome to SEA TRIBE Roleplay');